package status

const (
	StatusCompleted       = "completed"
	StatusFinished        = "finished"
	StatusStarted         = "started"
	StatusFound           = "found"
	StatusFailed          = "failed"
	StatusSuccess         = "success"
	StatusSearching       = "searching"
	StatusPending         = "pending"
	StatusCancelled       = "cancelled"
	StatusInProgress      = "in_progress"
	StatusPaused          = "paused"
	StatusResumed         = "resumed"
	StatusWaiting         = "waiting"
	StatusInitializing    = "initializing"
	StatusError           = "error"
	StatusBlocked         = "blocked"
	StatusExpired         = "expired"
	StatusRejected        = "rejected"
	StatusApproved        = "approved"
	StatusWithdrawn       = "withdrawn"
	StatusValid           = "valid"
	StatusInvalid         = "invalid"
	StatusVerified        = "verified"
	StatusUnverified      = "unverified"
	StatusDisapproved     = "disapproved"
	StatusPendingReview   = "pending_review"
	StatusPendingApproval = "pending_approval"
	StatusActive          = "active"
	StatusInactive        = "inactive"
	StatusSuspended       = "suspended"
	StatusClosed          = "closed"
	StatusOpened          = "opened"
	StatusLocked          = "locked"
	StatusUnlocked        = "unlocked"
)
